import { Vazirmatn } from "next/font/google";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { cn } from "@/utils/cn";

import type { Metadata } from "next";
import "./globals.css";

const vazir = Vazirmatn({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "فروشگاه اینترنتی ایرانسل",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl" className="h-full">
      <body className={cn("relative h-full antialiased", vazir.className)}>
        <main className="relative flex min-h-screen flex-col">
          <Header />
          <div className="flex flex-grow items-center justify-center bg-bg-color">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
